build_in: build
type: img
name: kasm.guac.img
clear_build_path: true
next:
- build: docker
	build_in: docker
	config:
		image_name: eons/kasm.guac.img
		combine:
		- kasmweb/kasm-guac:1.15.0
		image_os: debian
		also:
		- RUN mkdir -p /opt/kasm/current/tmp/guac
		- RUN chown -R kasm:kasm /opt/kasm/
		- RUN mkdir /home/kasm
		- RUN chown -R kasm:kasm /home/kasm
		- USER kasm
		entrypoint: "/dockerentrypoint.sh"
		tags: 
		- "1.15.0"
		- latest
- build: docker_publish
	run_when_any:
	- release
	build_in: publish
	config:
		image_name: eons/kasm.guac.img
